import '../styles/main.css';
import '@rainbow-me/rainbowkit/styles.css';
import type { AppProps } from 'next/app';
import { RainbowKitProvider, getDefaultWallets } from '@rainbow-me/rainbowkit';
import { configureChains, createClient, useAccount, WagmiConfig } from 'wagmi';
import { mainnet, polygon, optimism, baseGoerli, optimismGoerli, arbitrum, goerli, polygonMumbai } from 'wagmi/chains';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';
import { ApolloProvider, ApolloClient, InMemoryCache, gql } from '@apollo/client';
import Head from 'next/head';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import FooterMenu from '../components/FooterMenu';
import { PLAYDAOGlobals } from '../util/hooks'

const { chains, provider, webSocketProvider } = configureChains(
  [
    goerli,
    baseGoerli,
    polygonMumbai,
    optimismGoerli,
    // ...(process.env.NEXT_PUBLIC_ENABLE_TESTNETS === 'true' ? [goerli] : []),
  ],
  [
    alchemyProvider({
      // This is Alchemy's default API key.
      // You can get your own at https://dashboard.alchemyapi.io
      apiKey: "IccI4wsgF0qeGPn7IkdedKP8rL6-RWZx",
    }),
    publicProvider(),
  ]
);


const { connectors } = getDefaultWallets({
  appName: 'RainbowKit App',
  chains,
});


const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
  webSocketProvider,
});


const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: PLAYDAOGlobals().GRAPH_API
});

function MyApp({ Component, pageProps }: AppProps) {

  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <ApolloProvider client={client}>
          <main className='w-full h-auto bg-black'>
            <div className='w-auto max-w-lg  mx-auto relative '>
              <div className='relative z-10 min-h-screen w-full text-black text-xl flex flex-col content-center justify-center h-auto pb-24'>
                <div className='z-20 relative w-full h-24 flex items-center content-center justify-center bg-black'>
                  <img src='./logo.svg' className='m-0 h-full w-auto'></img>
                </div>
                {/* background: 'linear-gradient(45deg, red, #8d00ff)' */}
                <div className='bg-white min-h-screen relative flex flex-col h-auto p-6 rounded-2xl overflow-x-hidden z-10'>
                  <div className='flex flex-col items-center w-full mb-12'>
                    <ConnectButton />
                  </div>
                  <Head>
                    <title>playdao.ai</title>
                    <meta
                      name="description"
                      content="Generated by @rainbow-me/create-rainbowkit"
                    />
                    <link rel="icon" href="/favicon.ico" />

                  </Head>
                  <Component {...pageProps} />
                  <FooterMenu></FooterMenu>
                </div>
                <div style={{ width: '140%', left: '-20%', top: '20%' }} className='absolute top-20 w-full h-20 left-0 z-0'>
                  <img src='./side-goo.svg' className='m-0 w-full h-auto'></img>
                </div>
              </div>

            </div>

          </main>
        </ApolloProvider>
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;
