import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import FooterMenu from '../components/FooterMenu';
import ShareOrganizationView from '../components/ShareOrganizationView'
import QuestListView from '../components/QuestListView'

const Main: NextPage = () => {
	return (
		<div className=' bg-base-900 min-h-screen p-6 w-full text-base-100 text-xl'>
			<Head>
				<title>playdao.ai</title>
				<meta
					name="description"
					content="Generated by @rainbow-me/create-rainbowkit"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className='flex flex-col items-center w-full'>
					<ConnectButton />
				</div>
				<div className='flex flex-col w-full p-4'>
					{/* <ShareOrganizationView /> */}
					<QuestListView />


				</div>
			</main>
			<FooterMenu></FooterMenu>

		</div>
	);
};

export default Main;
